# This file was automatically generated by SWIG
package fasta_extract;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package fasta_extract;
bootstrap fasta_extract;
var_fasta_extract_init();
package fasta_extract;
@EXPORT = qw(seq_extract strncpychk  );
1;
