# This file was automatically generated by SWIG
package fasta_extract;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package fasta_extract;
bootstrap fasta_extract;
var_fasta_extract_init();
package fasta_extract;
@EXPORT = qw(seq_extract get_info $HEADERSIZE $FSTA_ENTIRE $FSTA_NO_OPEN $FSTA_OPEN_ONLY $FSTA_NO_CLOSE $FSTA_CLOSE_ONLY $ERR_SUPPRESS $NO_MATCH $OPEN_ERR $STAT_ERR $MMAP_ERR $REGEXP_COMP_ERR $MALLOC_ERR $NO_EOL strncpychk extract_info_header_set extract_info_header_get extract_info_file_offset_set extract_info_file_offset_get extract_info_regex_flags_set extract_info_regex_flags_get extract_info_match_set extract_info_match_get extract_info_n_match_set extract_info_n_match_get extract_info_err_set extract_info_err_get extract_info_flags_set extract_info_flags_get extract_info_mmem_set extract_info_mmem_get  );
1;
